#!/usr/bin/env python3
"""Generic builder: a form SPEC (JSON) -> importable n8n workflow JSON.

Usage:  python3 n8n/build_form_workflow.py n8n/specs/<slug>.json
Emits:  n8n/<slug>.workflow.json   (validated to parse before writing)

The spec is produced by reading a Jira form's screenshots (see the
migration-form-to-n8n skill / /migrate-form). One generic Code-node body is
emitted for every form (data-driven by the embedded FIELDS/TITLE/MEMBER_MAP),
so the only thing that varies between forms is the spec.

SPEC shape (all secrets/IDs stay as placeholders in the output):
{
  "slug": "arh-anyur-request",
  "workflow_name": "ARH · ANYUR REQUEST → Plane work item",
  "form_title": "....",                 # verbatim, not translated
  "form_description": "",
  "project_identifier": "ARH",          # used in the completion reference (ARH-123)
  "project_uuid": "ef603ac8-...",       # shown in the sticky note (URL keeps a placeholder)
  "workspace_slug": "hijra",
  "title_template": "Anyur {PILIHAN KEPERLUAN ANYUR} – {NAMA NASABAH}",
  "priority": "none",                   # urgent|high|medium|low|none
  "assignee_field": "ATASAN USER",      # "" / null when the form has no user picker
  "member_map": {"Danny Dwi Cahyono (dcahyono@hijra.id)": "f799f9fe-..."},
  "date_mappings": {"TANGGAL JATUH TEMPO": "target_date"},  # form date field -> Plane date
  "fields": [
    {"label":"NAMA NASABAH","n8n_type":"text","required":true,
     "placeholder":"...","options":[],"multiselect":false,"is_link":false}
  ],
  "manual_flags": ["..."]               # things that need a human (attachments, cascade, ...)
}
"""
import json
import sys
import uuid

VALID_TYPES = {"text", "textarea", "number", "date", "email", "dropdown"}


def nid():
    return str(uuid.uuid4())


# Data-driven Code-node body. __TOKENS__ are replaced with json.dumps(...) values.
# NOTE: n8n task-runner sandbox blocks require('crypto'); this code needs none.
CODE_JS_TEMPLATE = r"""// Generated by build_form_workflow.py — form submission -> Plane work item payload.
// Plane create body: name (required), description_html, priority,
// assignees[] (member UUIDs), target_date/start_date (YYYY-MM-DD).
const f = $json;

const FIELDS         = __FIELDS__;          // [{label, isLink}]
const ASSIGNEE_FIELD = __ASSIGNEE_FIELD__;  // "" or the user-picker field label
const MEMBER_MAP     = __MEMBER_MAP__;      // friendly label -> Plane member UUID
const TITLE_TEMPLATE = __TITLE_TEMPLATE__;  // uses {FIELD LABEL} tokens
const PRIORITY       = __PRIORITY__;        // urgent|high|medium|low|none
const STATE          = __STATE__;           // Plane state UUID (intake); "" -> project default
const LABELS             = __LABELS__;             // label UUIDs attached to every submission
const CHOICE_LABEL_FIELD = __CHOICE_LABEL_FIELD__; // field whose option adds a label ("" = none)
const CHOICE_LABEL_MAP   = __CHOICE_LABEL_MAP__;   // {option text: label UUID}
const MODULE_FIELD       = __MODULE_FIELD__;       // field whose option maps to a module ("" = none)
const MODULE_MAP         = __MODULE_MAP__;         // {option text: module UUID}
const DUE_IN_DAYS        = __DUE_IN_DAYS__;         // -1 disables auto dates
const DATE_MAPPINGS      = __DATE_MAPPINGS__;       // {field label: "target_date"|"start_date"}

const get = (l) => (f[l] == null ? '' : String(f[l])).trim();
const esc = (s) => String(s == null ? '' : s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const linkify = (u) => {
  const s = String(u || '').trim();
  if (!s) return '<em>(kosong)</em>';
  return /^https?:\/\//i.test(s) ? ('<a href="' + esc(s) + '">' + esc(s) + '</a>') : esc(s);
};

// --- Title ---
let name = TITLE_TEMPLATE.replace(/\{([^}]+)\}/g, (_, k) => get(k)).replace(/\s+/g, ' ').trim();
if (!name) name = (get((FIELDS[0] || {}).label) || 'Untitled');

// --- Assignee (hit -> set; miss -> capture in description) ---
let assignees = [];
let unresolvedAssignee = '';
if (ASSIGNEE_FIELD) {
  const lbl = get(ASSIGNEE_FIELD);
  if (MEMBER_MAP[lbl]) assignees = [MEMBER_MAP[lbl]];
  else if (lbl) unresolvedAssignee = lbl;
}

// --- Description (HTML) — one row per field, links clickable ---
const rows = [];
for (const fld of FIELDS) {
  if (fld.label === ASSIGNEE_FIELD) continue;     // shown via assignee handling
  if (DATE_MAPPINGS[fld.label]) continue;          // promoted to a Plane date field
  const v = get(fld.label);
  rows.push('<p><strong>' + esc(fld.label) + ':</strong> '
    + (fld.isLink ? ('<br/>' + linkify(v)) : esc(v)) + '</p>');
}
if (unresolvedAssignee) {
  rows.push('<p><strong>' + esc(ASSIGNEE_FIELD)
    + ' (belum terpetakan ke member Plane):</strong> ' + esc(unresolvedAssignee) + '</p>');
}
const description_html = rows.join('\n');

// --- Labels: always-on + choice-driven ---
let labels = LABELS.slice();
if (CHOICE_LABEL_FIELD) {
  const id = CHOICE_LABEL_MAP[get(CHOICE_LABEL_FIELD)];
  if (id && labels.indexOf(id) < 0) labels.push(id);
}

// --- Plane create body ---
const body = {
  name: name,
  description_html: description_html,
  priority: PRIORITY,
  assignees: assignees,
};
if (STATE) body.state = STATE;             // pin intake state (else Plane uses project default)
if (labels.length) body.labels = labels;

// Auto dates: start = today, due = today + DUE_IN_DAYS. Computed in Asia/Jakarta
// (UTC+7, no DST) so "today" is correct regardless of the n8n server timezone.
if (DUE_IN_DAYS >= 0) {
  const _pad = (n) => String(n).padStart(2, '0');
  const _ymd = (d) => d.getUTCFullYear() + '-' + _pad(d.getUTCMonth() + 1) + '-' + _pad(d.getUTCDate());
  const _jkt = new Date(Date.now() + 7 * 3600 * 1000);
  body.start_date = _ymd(_jkt);
  body.target_date = _ymd(new Date(_jkt.getTime() + DUE_IN_DAYS * 86400000));
}

// Explicit form date fields (if any) override the auto dates.
for (const lbl of Object.keys(DATE_MAPPINGS)) {
  const v = get(lbl);
  if (v) body[DATE_MAPPINGS[lbl]] = v;   // n8n date field yields YYYY-MM-DD
}

// Module is set via a second call (Plane create takes no module); resolve its UUID
// from the chosen category. Empty -> the "Add to module" node (if any) is a no-op.
let module_id = '';
if (MODULE_FIELD) module_id = MODULE_MAP[get(MODULE_FIELD)] || '';

return { body: body, module_id: module_id };
"""


def build_code_js(spec, member_map):
    fields_manifest = [
        {"label": fld["label"], "isLink": bool(fld.get("is_link"))}
        for fld in spec["fields"]
    ]
    repl = {
        "__FIELDS__": json.dumps(fields_manifest, ensure_ascii=False),
        "__ASSIGNEE_FIELD__": json.dumps(spec.get("assignee_field") or "", ensure_ascii=False),
        "__MEMBER_MAP__": json.dumps(member_map, ensure_ascii=False),
        "__TITLE_TEMPLATE__": json.dumps(spec["title_template"], ensure_ascii=False),
        "__PRIORITY__": json.dumps(spec.get("priority") or "none", ensure_ascii=False),
        "__STATE__": json.dumps(spec.get("state_id") or "", ensure_ascii=False),
        "__DUE_IN_DAYS__": json.dumps(3 if spec.get("due_in_days") is None else spec["due_in_days"]),
        "__LABELS__": json.dumps(spec.get("auto_label_ids") or [], ensure_ascii=False),
        "__CHOICE_LABEL_FIELD__": json.dumps(spec.get("choice_label_field") or "", ensure_ascii=False),
        "__CHOICE_LABEL_MAP__": json.dumps(spec.get("choice_label_map") or {}, ensure_ascii=False),
        "__MODULE_FIELD__": json.dumps(spec.get("module_field") or "", ensure_ascii=False),
        "__MODULE_MAP__": json.dumps(spec.get("module_map") or {}, ensure_ascii=False),
        "__DATE_MAPPINGS__": json.dumps(spec.get("date_mappings") or {}, ensure_ascii=False),
    }
    js = CODE_JS_TEMPLATE
    for k, v in repl.items():
        js = js.replace(k, v)
    return js


def build_form_fields(spec, member_map):
    assignee_field = spec.get("assignee_field") or ""
    values = []
    for fld in spec["fields"]:
        ftype = fld["n8n_type"]
        if ftype not in VALID_TYPES:
            raise ValueError("bad n8n_type %r for field %r" % (ftype, fld.get("label")))
        node = {
            "fieldLabel": fld["label"],
            "fieldType": ftype,
            "requiredField": bool(fld.get("required")),
        }
        ph = fld.get("placeholder")
        if ph:
            node["placeholder"] = ph
        # The user-picker becomes a dropdown of friendly member labels.
        if fld["label"] == assignee_field:
            node["fieldType"] = "dropdown"
            node["fieldOptions"] = {"values": [{"option": k} for k in member_map.keys()]}
        elif ftype == "dropdown":
            node["fieldOptions"] = {"values": [{"option": o} for o in fld.get("options", [])]}
            if fld.get("multiselect"):
                node["multiselect"] = True
        values.append(node)
    return {"values": values}


def build_workflow(spec):
    member_map = spec.get("member_map") or {}
    ws = spec.get("workspace_slug") or "hijra"
    ident = spec.get("project_identifier") or "ITEM"
    proj_uuid = spec.get("project_uuid") or "PLANE_TARGET_PROJECT_ID"

    code_js = build_code_js(spec, member_map)
    form_fields = build_form_fields(spec, member_map)

    # Reference the create node explicitly so the message works whether or not an
    # "Add to module" node sits between create and the completion screen.
    completion_message = (
        "=Created " + ident
        + "-{{ $('Create Plane work item').first().json.sequence_id }} · "
        "https://YOUR_PLANE_BASE/" + ws
        + "/projects/PLANE_TARGET_PROJECT_ID/issues/{{ $('Create Plane work item').first().json.id }}"
    )

    has_module = bool(spec.get("module_field") and spec.get("module_map"))

    members_lines = "".join(
        "- `%s` → `%s`\n" % (label, uid) for label, uid in member_map.items()
    ) or "- (none yet)\n"
    flags = spec.get("manual_flags") or []
    flags_md = ("\n### Manual / needs attention\n" + "".join("- %s\n" % x for x in flags)) if flags else ""
    state_md = ""
    if spec.get("state_id"):
        state_md = "- new items created in state **%s** (`%s`)\n" % (
            spec.get("state_name") or "?", spec["state_id"])
    labels_md = ""
    if spec.get("auto_label_ids"):
        names = spec.get("auto_label_names") or []
        labels_md = "- auto-labels: %s\n" % (", ".join(names) if names else "%d label(s)" % len(spec["auto_label_ids"]))
    module_md = ""
    if has_module:
        module_md = (
            "- module: the chosen **%s** is matched by name to a module (via the "
            "'Add to module' node, set to continue-on-fail)\n" % spec["module_field"])
    choice_label_md = ""
    if spec.get("choice_label_field") and spec.get("choice_label_map"):
        choice_label_md = "- choice-label: certain **%s** options also add a matching label (%s)\n" % (
            spec["choice_label_field"], ", ".join(spec["choice_label_map"].keys()))

    sticky = (
        "## " + ident + " form → Plane\n"
        "Fill the PLACEHOLDERS before enabling:\n"
        "- **URL host** `YOUR_PLANE_BASE`\n"
        "- **`PLANE_TARGET_PROJECT_ID`** → `" + proj_uuid + "` (" + ident + ")\n"
        "- **`YOUR_PLANE_API_KEY`** → Plane token (X-API-Key)\n"
        "- workspace slug = `" + ws + "`\n"
        + state_md + labels_md + choice_label_md + module_md + "\n"
        "### Assignee dropdown (snapshot of Plane members)\n"
        "Dropdown shows friendly labels; the Code node's MEMBER_MAP resolves the choice\n"
        "to a member UUID (hit → assignee; miss → captured in the description). Add BOTH a\n"
        "dropdown option AND a MEMBER_MAP entry (identical strings) as people sign up:\n"
        + members_lines
        + flags_md
    )

    form_trigger = nid()
    code_id = nid()
    http_id = nid()
    module_node_id = nid()
    completion_id = nid()

    ending_x = 900 if has_module else 720
    module_node = {
        "parameters": {
            "method": "POST",
            "url": "https://YOUR_PLANE_BASE/api/v1/workspaces/" + ws
            + "/projects/PLANE_TARGET_PROJECT_ID/modules/"
            + "{{ $('Map → Plane payload').first().json.module_id }}/module-issues/",
            "sendHeaders": True,
            "headerParameters": {
                "parameters": [
                    {"name": "X-API-Key", "value": "YOUR_PLANE_API_KEY"},
                    {"name": "Content-Type", "value": "application/json"},
                ]
            },
            "sendBody": True,
            "specifyBody": "json",
            "jsonBody": '={{ { "issues": [$json.id] } }}',
            "options": {},
        },
        "id": module_node_id,
        "name": "Add to module",
        "type": "n8n-nodes-base.httpRequest",
        "typeVersion": 4.2,
        "position": [690, 0],
        # don't fail the whole submission if the module link can't be set
        "onError": "continueRegularOutput",
    }

    workflow = {
        "name": spec.get("workflow_name") or (ident + " form → Plane work item"),
        "nodes": [
            {
                "parameters": {
                    "formTitle": spec["form_title"],
                    "formDescription": spec.get("form_description") or "",
                    "formFields": form_fields,
                    "options": {},
                },
                "id": form_trigger,
                "name": "On form submission",
                "type": "n8n-nodes-base.formTrigger",
                "typeVersion": 2.2,
                "position": [0, 0],
                "webhookId": nid(),
            },
            {
                "parameters": {
                    "mode": "runOnceForEachItem",
                    "language": "javaScript",
                    "jsCode": code_js,
                },
                "id": code_id,
                "name": "Map → Plane payload",
                "type": "n8n-nodes-base.code",
                "typeVersion": 2,
                "position": [240, 0],
            },
            {
                "parameters": {
                    "method": "POST",
                    "url": "https://YOUR_PLANE_BASE/api/v1/workspaces/" + ws
                    + "/projects/PLANE_TARGET_PROJECT_ID/issues/",
                    "sendHeaders": True,
                    "headerParameters": {
                        "parameters": [
                            {"name": "X-API-Key", "value": "YOUR_PLANE_API_KEY"},
                            {"name": "Content-Type", "value": "application/json"},
                        ]
                    },
                    "sendBody": True,
                    "specifyBody": "json",
                    "jsonBody": "={{ $json.body }}",
                    "options": {},
                },
                "id": http_id,
                "name": "Create Plane work item",
                "type": "n8n-nodes-base.httpRequest",
                "typeVersion": 4.2,
                "position": [480, 0],
            },
            {
                "parameters": {
                    "operation": "completion",
                    "completionTitle": "Permintaan berhasil dibuat",
                    "completionMessage": completion_message,
                    "options": {},
                },
                "id": completion_id,
                "name": "Form ending",
                "type": "n8n-nodes-base.form",
                "typeVersion": 1,
                "position": [ending_x, 0],
            },
            {
                "parameters": {"content": sticky, "height": 360, "width": 480},
                "id": nid(),
                "name": "READ ME — placeholders",
                "type": "n8n-nodes-base.stickyNote",
                "typeVersion": 1,
                "position": [-40, -300],
            },
        ],
        "connections": {
            "On form submission": {"main": [[{"node": "Map → Plane payload", "type": "main", "index": 0}]]},
            "Map → Plane payload": {"main": [[{"node": "Create Plane work item", "type": "main", "index": 0}]]},
        },
        "active": False,
        "settings": {"executionOrder": "v1"},
        "pinData": {},
        "meta": {"templateId": spec.get("slug") or "form-to-plane"},
    }

    # Create → (Add to module →) Form ending
    if has_module:
        workflow["nodes"].append(module_node)
        workflow["connections"]["Create Plane work item"] = {
            "main": [[{"node": "Add to module", "type": "main", "index": 0}]]}
        workflow["connections"]["Add to module"] = {
            "main": [[{"node": "Form ending", "type": "main", "index": 0}]]}
    else:
        workflow["connections"]["Create Plane work item"] = {
            "main": [[{"node": "Form ending", "type": "main", "index": 0}]]}

    return workflow


def main(spec_path):
    with open(spec_path, encoding="utf-8") as fh:
        spec = json.load(fh)
    slug = spec.get("slug") or "form-to-plane"
    wf = build_workflow(spec)
    text = json.dumps(wf, indent=2, ensure_ascii=False)
    json.loads(text)  # validate
    out = "n8n/%s.workflow.json" % slug
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(text + "\n")
    print("OK", out, "(", len(text), "bytes )",
          "fields=", len(wf["nodes"][0]["parameters"]["formFields"]["values"]))
    return out


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: build_form_workflow.py <spec.json>")
    main(sys.argv[1])
