#!/usr/bin/env python3
"""Generic builder: a form SPEC (JSON) -> importable n8n workflow JSON.

Usage:  python3 n8n/build_form_workflow.py n8n/specs/<slug>.json
Emits:  n8n/<slug>.workflow.json   (validated to parse before writing)

The spec is produced by reading a Jira form's screenshots (see the
migration-form-to-n8n skill / /migrate-form). One generic Code-node body is
emitted for every form (data-driven by the embedded FIELDS/TITLE/MEMBER_MAP),
so the only thing that varies between forms is the spec.

SPEC shape (all secrets/IDs stay as placeholders in the output):
{
  "slug": "arh-anyur-request",
  "workflow_name": "ARH · ANYUR REQUEST → Plane work item",
  "form_title": "....",                 # verbatim, not translated
  "form_description": "",
  "project_identifier": "ARH",          # used in the completion reference (ARH-123)
  "project_uuid": "ef603ac8-...",       # shown in the sticky note (URL keeps a placeholder)
  "workspace_slug": "hijra",
  "title_template": "Anyur {PILIHAN KEPERLUAN ANYUR} – {NAMA NASABAH}",
  "priority": "none",                   # urgent|high|medium|low|none
  "assignee_field": "ATASAN USER",      # "" / null when the form has no user picker
  "member_map": {"Danny Dwi Cahyono (dcahyono@hijra.id)": "f799f9fe-..."},
  "date_mappings": {"TANGGAL JATUH TEMPO": "target_date"},  # form date field -> Plane date
  "fields": [
    {"label":"NAMA NASABAH","n8n_type":"text","required":true,
     "placeholder":"...","options":[],"multiselect":false,"is_link":false}
  ],
  "manual_flags": ["..."]               # things that need a human (attachments, cascade, ...)
}
"""
import json
import sys
import uuid

VALID_TYPES = {"text", "textarea", "number", "date", "email", "dropdown"}


def nid():
    return str(uuid.uuid4())


# Data-driven Code-node body. __TOKENS__ are replaced with json.dumps(...) values.
# NOTE: n8n task-runner sandbox blocks require('crypto'); this code needs none.
CODE_JS_TEMPLATE = r"""// Generated by build_form_workflow.py — form submission -> Plane work item payload.
// Plane create body: name (required), description_html, priority,
// assignees[] (member UUIDs), target_date/start_date (YYYY-MM-DD).
const f = $json;

const FIELDS         = __FIELDS__;          // [{label, isLink}]
const ASSIGNEE_FIELD = __ASSIGNEE_FIELD__;  // "" or the user-picker field label
const MEMBER_MAP     = __MEMBER_MAP__;      // friendly label -> Plane member UUID
const TITLE_TEMPLATE = __TITLE_TEMPLATE__;  // uses {FIELD LABEL} tokens
const PRIORITY       = __PRIORITY__;        // urgent|high|medium|low|none
const DATE_MAPPINGS  = __DATE_MAPPINGS__;   // {field label: "target_date"|"start_date"}

const get = (l) => (f[l] == null ? '' : String(f[l])).trim();
const esc = (s) => String(s == null ? '' : s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const linkify = (u) => {
  const s = String(u || '').trim();
  if (!s) return '<em>(kosong)</em>';
  return /^https?:\/\//i.test(s) ? ('<a href="' + esc(s) + '">' + esc(s) + '</a>') : esc(s);
};

// --- Title ---
let name = TITLE_TEMPLATE.replace(/\{([^}]+)\}/g, (_, k) => get(k)).replace(/\s+/g, ' ').trim();
if (!name) name = (get((FIELDS[0] || {}).label) || 'Untitled');

// --- Assignee (hit -> set; miss -> capture in description) ---
let assignees = [];
let unresolvedAssignee = '';
if (ASSIGNEE_FIELD) {
  const lbl = get(ASSIGNEE_FIELD);
  if (MEMBER_MAP[lbl]) assignees = [MEMBER_MAP[lbl]];
  else if (lbl) unresolvedAssignee = lbl;
}

// --- Description (HTML) — audit trail of every field ---
const rows = [];
for (const fld of FIELDS) {
  if (fld.label === ASSIGNEE_FIELD) continue;     // shown via assignee handling
  if (DATE_MAPPINGS[fld.label]) continue;          // promoted to a Plane date field
  const v = get(fld.label);
  rows.push('<p><strong>' + esc(fld.label) + ':</strong> '
    + (fld.isLink ? ('<br/>' + linkify(v)) : esc(v)) + '</p>');
}
if (unresolvedAssignee) {
  rows.push('<p><strong>' + esc(ASSIGNEE_FIELD)
    + ' (belum terpetakan ke member Plane):</strong> ' + esc(unresolvedAssignee) + '</p>');
}
rows.push('<hr/>');
rows.push('<p><em>Dibuat via n8n form.</em></p>');
const description_html = rows.join('\n');

// --- Plane create body ---
const body = {
  name: name,
  description_html: description_html,
  priority: PRIORITY,
  assignees: assignees,
};
for (const lbl of Object.keys(DATE_MAPPINGS)) {
  const v = get(lbl);
  if (v) body[DATE_MAPPINGS[lbl]] = v;   // n8n date field yields YYYY-MM-DD
}

return { body: body };
"""


def build_code_js(spec, member_map):
    fields_manifest = [
        {"label": fld["label"], "isLink": bool(fld.get("is_link"))}
        for fld in spec["fields"]
    ]
    repl = {
        "__FIELDS__": json.dumps(fields_manifest, ensure_ascii=False),
        "__ASSIGNEE_FIELD__": json.dumps(spec.get("assignee_field") or "", ensure_ascii=False),
        "__MEMBER_MAP__": json.dumps(member_map, ensure_ascii=False),
        "__TITLE_TEMPLATE__": json.dumps(spec["title_template"], ensure_ascii=False),
        "__PRIORITY__": json.dumps(spec.get("priority") or "none", ensure_ascii=False),
        "__DATE_MAPPINGS__": json.dumps(spec.get("date_mappings") or {}, ensure_ascii=False),
    }
    js = CODE_JS_TEMPLATE
    for k, v in repl.items():
        js = js.replace(k, v)
    return js


def build_form_fields(spec, member_map):
    assignee_field = spec.get("assignee_field") or ""
    values = []
    for fld in spec["fields"]:
        ftype = fld["n8n_type"]
        if ftype not in VALID_TYPES:
            raise ValueError("bad n8n_type %r for field %r" % (ftype, fld.get("label")))
        node = {
            "fieldLabel": fld["label"],
            "fieldType": ftype,
            "requiredField": bool(fld.get("required")),
        }
        ph = fld.get("placeholder")
        if ph:
            node["placeholder"] = ph
        # The user-picker becomes a dropdown of friendly member labels.
        if fld["label"] == assignee_field:
            node["fieldType"] = "dropdown"
            node["fieldOptions"] = {"values": [{"option": k} for k in member_map.keys()]}
        elif ftype == "dropdown":
            node["fieldOptions"] = {"values": [{"option": o} for o in fld.get("options", [])]}
            if fld.get("multiselect"):
                node["multiselect"] = True
        values.append(node)
    return {"values": values}


def build_workflow(spec):
    member_map = spec.get("member_map") or {}
    ws = spec.get("workspace_slug") or "hijra"
    ident = spec.get("project_identifier") or "ITEM"
    proj_uuid = spec.get("project_uuid") or "PLANE_TARGET_PROJECT_ID"

    code_js = build_code_js(spec, member_map)
    form_fields = build_form_fields(spec, member_map)

    completion_message = (
        "=Created " + ident + "-{{ $json.sequence_id }} · "
        "https://YOUR_PLANE_BASE/" + ws + "/projects/PLANE_TARGET_PROJECT_ID/issues/{{ $json.id }}"
    )

    members_lines = "".join(
        "- `%s` → `%s`\n" % (label, uid) for label, uid in member_map.items()
    ) or "- (none yet)\n"
    flags = spec.get("manual_flags") or []
    flags_md = ("\n### Manual / needs attention\n" + "".join("- %s\n" % x for x in flags)) if flags else ""

    sticky = (
        "## " + ident + " form → Plane\n"
        "Fill the PLACEHOLDERS before enabling:\n"
        "- **URL host** `YOUR_PLANE_BASE`\n"
        "- **`PLANE_TARGET_PROJECT_ID`** → `" + proj_uuid + "` (" + ident + ")\n"
        "- **`YOUR_PLANE_API_KEY`** → Plane token (X-API-Key)\n"
        "- workspace slug = `" + ws + "`\n\n"
        "### Assignee dropdown (snapshot of Plane members)\n"
        "Dropdown shows friendly labels; the Code node's MEMBER_MAP resolves the choice\n"
        "to a member UUID (hit → assignee; miss → captured in the description). Add BOTH a\n"
        "dropdown option AND a MEMBER_MAP entry (identical strings) as people sign up:\n"
        + members_lines
        + flags_md
    )

    form_trigger = nid()
    code_id = nid()
    http_id = nid()
    completion_id = nid()

    workflow = {
        "name": spec.get("workflow_name") or (ident + " form → Plane work item"),
        "nodes": [
            {
                "parameters": {
                    "formTitle": spec["form_title"],
                    "formDescription": spec.get("form_description") or "",
                    "formFields": form_fields,
                    "options": {},
                },
                "id": form_trigger,
                "name": "On form submission",
                "type": "n8n-nodes-base.formTrigger",
                "typeVersion": 2.2,
                "position": [0, 0],
                "webhookId": nid(),
            },
            {
                "parameters": {
                    "mode": "runOnceForEachItem",
                    "language": "javaScript",
                    "jsCode": code_js,
                },
                "id": code_id,
                "name": "Map → Plane payload",
                "type": "n8n-nodes-base.code",
                "typeVersion": 2,
                "position": [240, 0],
            },
            {
                "parameters": {
                    "method": "POST",
                    "url": "https://YOUR_PLANE_BASE/api/v1/workspaces/" + ws
                    + "/projects/PLANE_TARGET_PROJECT_ID/issues/",
                    "sendHeaders": True,
                    "headerParameters": {
                        "parameters": [
                            {"name": "X-API-Key", "value": "YOUR_PLANE_API_KEY"},
                            {"name": "Content-Type", "value": "application/json"},
                        ]
                    },
                    "sendBody": True,
                    "specifyBody": "json",
                    "jsonBody": "={{ $json.body }}",
                    "options": {},
                },
                "id": http_id,
                "name": "Create Plane work item",
                "type": "n8n-nodes-base.httpRequest",
                "typeVersion": 4.2,
                "position": [480, 0],
            },
            {
                "parameters": {
                    "operation": "completion",
                    "completionTitle": "Permintaan berhasil dibuat",
                    "completionMessage": completion_message,
                    "options": {},
                },
                "id": completion_id,
                "name": "Form ending",
                "type": "n8n-nodes-base.form",
                "typeVersion": 1,
                "position": [720, 0],
            },
            {
                "parameters": {"content": sticky, "height": 360, "width": 480},
                "id": nid(),
                "name": "READ ME — placeholders",
                "type": "n8n-nodes-base.stickyNote",
                "typeVersion": 1,
                "position": [-40, -300],
            },
        ],
        "connections": {
            "On form submission": {"main": [[{"node": "Map → Plane payload", "type": "main", "index": 0}]]},
            "Map → Plane payload": {"main": [[{"node": "Create Plane work item", "type": "main", "index": 0}]]},
            "Create Plane work item": {"main": [[{"node": "Form ending", "type": "main", "index": 0}]]},
        },
        "active": False,
        "settings": {"executionOrder": "v1"},
        "pinData": {},
        "meta": {"templateId": spec.get("slug") or "form-to-plane"},
    }
    return workflow


def main(spec_path):
    with open(spec_path, encoding="utf-8") as fh:
        spec = json.load(fh)
    slug = spec.get("slug") or "form-to-plane"
    wf = build_workflow(spec)
    text = json.dumps(wf, indent=2, ensure_ascii=False)
    json.loads(text)  # validate
    out = "n8n/%s.workflow.json" % slug
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(text + "\n")
    print("OK", out, "(", len(text), "bytes )",
          "fields=", len(wf["nodes"][0]["parameters"]["formFields"]["values"]))
    return out


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: build_form_workflow.py <spec.json>")
    main(sys.argv[1])
